[package]
name = "slack"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
doctest = false

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
chat-core = { package = "core", path = "../../core" }
chrono.workspace = true
futures-util = "0.3"
serde.workspace = true
serde_json = "1"
tokio.workspace = true
tokio-tungstenite = { version = "0.27", features = ["rustls-tls-webpki-roots"] }
ureq = { version = "3", features = ["json"] }
