[package]
name = "slack"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
doctest = false

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
chat-core = { package = "core", path = "../../core" }
chrono.workspace = true
serde.workspace = true
tokio.workspace = true
ureq = { version = "3", features = ["json"] }
